### ISSUE TITLE
新思路

### ISSUE THREAD

**Issue by happypeter** [happypeter/offline-happycasts#10]
把这个应用，按 github 的 issue 来做。给出几个标签例如：

`Ask Happycasts` `new Event` ...

这个项目讲作为我 https://github.com/happypeter/rails10 课程的实例项目。

**Comment by happypeter** [comment]
首页的内容就是一个列表，简单的不能再傻瓜了。所以设计上可以高达上一些：https://medium.com/m/welcome
http://www.dadaabstories.org/

**Comment by happypeter** [comment]
tag 其实不必有，大家想发什么就发什么吧。只要有 issue 关闭功能就好。

其实群发邮件，查询任何一个同学的邮件都是很有用的。

**Comment by happypeter** [comment]
@july-12 我看你刚才又 fork 了这个项目了，先不要动手弄。我这两天刚刚弄了一个新版本的网站，过两天会把代码传到这里来。

**Comment by happypeter** [comment]
@july-12 新代码已经传上来了，不过代码还没开发完成，所以也还没有部署。

**Comment by july-12** [comment]
@happypeter  我先把新版本pull下来了，现在要进行的任务开发添加“类issue”功能吗？

**Comment by july-12** [comment]
@happypeter 我能ignore database.yml吗？ 我想在本地用postgresql

**Comment by july-12** [comment]
@happypeter 我把程序跑了一下， UI着实高大了不少啊， 感觉特别好！

**Comment by happypeter** [comment]
@july-12 我现在还在频繁的改动代码，所以你那边先不要动了。

**Comment by july-12** [comment]
@happypeter 好的。
