### ISSUE TITLE
theme

### ISSUE THREAD

**Issue by happypeter** [happypeter/offline-happycasts#13]
http://wrapbootstrap.com/preview/WB0B30DGR

自己的脑子还是想不出成套的色彩方案，还是参考人家的吧

**Comment by july-12** [comment]
我觉得应该和happycasts统一

**Comment by happypeter** [comment]
@july-12 很有道理

**Comment by july-12** [comment]
@happypeter 有什么的新的想法想加进去。

**Comment by happypeter** [comment]
@july-12 你改一下配色方案吧，改的跟 happycasts 有一种亲属的感觉。

可以到 https://wrapbootstrap.com/ 上选一套 theme 来参考。尽量选择扁平风格。

**Comment by july-12** [comment]
@happypeter 只是参考， 不能直接download源码来用吗？

**Comment by happypeter** [comment]
咱们的应用非常简单，download 源码下来也用不了，适当地参考一下就可以了。要自己一行行手写，这样才能学到东西。
