### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by happypeter** [happypeter/offline-happycasts#3]

**Comment by happypeter** [comment]
With https://github.com/happypeter/offline-happycasts/pull/4

now we can leave comments, but markdown is not supported yet.

so @july-12, can you plz add markdown support for us. Ref to: https://github.com/happypeter/offline-happycasts/commit/c75dda5074da8c9094c0970c85f057a9eb8c7a2e

**Comment by july-12** [comment]
Ok, No problem!  I try my best, then pack it in me!

**Comment by july-12** [comment]
@happypeter  comments markdown support have pull request for you, complete easy,  because you have define markdown() method, I just call that.
next, I want to add users mic-posts or some social,  what do you think?

**Comment by happypeter** [comment]
@july-12 Are you interested in doing some CSS work to make comments pretty?

**Comment by july-12** [comment]
Yes,  I interested, because I am a people with aesthetic feeling， O(∩_∩)O. but I have mush skill for CSS, Peter can you give me some way to learn it!

**Comment by happypeter** [comment]
http://learn.shayhowe.com/

Best CSS beginner's guide I ever seen.

**Comment by july-12** [comment]
Ok, next task I will add CSS !

**Comment by july-12** [comment]
@happypeter  Can I use "Twitter Bootstrap"  gem.

**Comment by happypeter** [comment]
@july-12 No

**Comment by july-12** [comment]
@happypeter  what is next task ?

**Comment by happypeter** [comment]
@july-12 

Could you plz make the comment box a bit prettier, make it looks like the comment box here.

try to use time_ago_in_words gem.

**Comment by july-12** [comment]
yes I can!
