### ISSUE TITLE
http://brackets.io/

### ISSUE THREAD

**Issue by happypeter** [happypeter/offline-happycasts#37]
http://brackets.io/ 首页上还真有 “Live Preview”，如果配置很方便的话，就着一个功能我觉得就很值得用用了。 @luckyyang

**Comment by happypeter** [comment]
静态页面的实时刷新叫 live preview， rails 或者 jekyll 的刷新就是 live reload 了。

html 页面 live preview 功能 atom 有包直接支持，挺好用。

live reload 未来我觉得还是用 grunt 比较好：http://css-tricks.com/video-screencasts/screencast-134-tour-site-progress-built-jekyll-grunt-sass-svg-system/?play=true

**Comment by happypeter** [comment]
保持关注。

**Comment by luckyyang** [comment]
atom我暂时用不了，先用用brackets

**Comment by luckyyang** [comment]
grunt不错，值得学习学习
