### ISSUE TITLE
我的关于rails入门的提问

### ISSUE THREAD

**Issue by Wellaiyo** [happypeter/offline-happycasts#38]
我之后的关于rails的单独的提问都会出现在这里

**Comment by Wellaiyo** [comment]
@happypeter

**Comment by Wellaiyo** [comment]
@happypeter 我怎么找不到你的个人博客happypeter.github.io 这个网站的文件托管在哪里了 ，我想看你的源文件 。上次你都给我看了 ，给个链接让我看下

**Comment by happypeter** [comment]
https://github.com/happypeter/happypeter.github.com

**Comment by happypeter** [comment]
引用其他服务器上的图片是可以的，例如我的 https://github.com/happypeter/drawing

**Comment by happypeter** [comment]
> 我点开网页查看元素 ，发现并没有发生改变 ，而且我还是特意等了半天才去查看的

如果是修改没有生效，那就跟图片在哪里没有关系了。一般是因为你的最新修改有错误，导致 jekyll 运行失败了，所以页面没有被更新。这种情况，你的邮箱里应该会收到报错邮件。

**Comment by Wellaiyo** [comment]
你的那个Linux for developer 我已经看完了 ，好多看不懂的我就跳过了。基本的命令我都抄下来了，不过你讲得有点快，一时难以消化。jekyll 那个我也已经写了一篇博客 ，不过关于主页和怎么将文章标题智能化的放在主页上我还在研究

**Comment by Wellaiyo** [comment]
最近事比较多 ，可能进度会稍微慢点，我还得研究一些js效果，所以比较忙。

**Comment by Wellaiyo** [comment]
@happypeter thankyou！

**Comment by Wellaiyo** [comment]
文章标题放在主页上应该是在你的tool文件夹里面的content.rb文件吧 ，但是我看不太懂，哪天你给我讲讲

**Comment by happypeter** [comment]
> 文章标题放在主页上应该是在你的tool文件夹里面的content.rb文件吧 

这个理解是错误的。是通过  https://raw.githubusercontent.com/happypeter/happypeter.github.com/master/index.markdown 文件中的，这几行自动生成的

```
  <ul class="posts">
    {% for post in site.posts %}
      <li><span>{{ post.date | date_to_string }}</span> &raquo; <a href="{{ post.url }}">{{ post.title }}</a></li>
    {% endfor %}
  </ul>
```

试着理解一下，不行下周二我可以给你当面演示一下。

**Comment by happypeter** [comment]
> 最近事比较多 ，可能进度会稍微慢点，我还得研究一些js效果，所以比较忙。

js 上花再多的时间都值，事实上如果 js 不好，入门 rails 也会有麻烦。

**Comment by Wellaiyo** [comment]
@happypeter 下周二我可能去不了了，我下周二要做汇报，4点才下课。如果下周三下午你有时间的话，咱们可以定在那时候（下周四也行）

**Comment by happypeter** [comment]
@Wellaiyo 那就暂定周三下午吧

**Comment by Wellaiyo** [comment]
@happypeter 我这边的事都结束了 ，可以开始征战rails了！

**Comment by Wellaiyo** [comment]
上次我学到哪一步我忘记了。。。。 你记得就给我提个醒呗

**Comment by happypeter** [comment]
学 http://sass-lang.com/

**Comment by Wellaiyo** [comment]
那我还是得摸索着在linux上做rails开发，因为sass要在ruby环境下才能用呀，是吗
发自我的小米手机
在 Peter Wang notifications@github.com，2015年1月12日 下午4:46写道：学 http://sass-lang.com/

**Comment by happypeter** [comment]
@Wellaiyo 不用，你用的 github pages 就是支持 sass 的

**Comment by Wellaiyo** [comment]
我还有个疑问，在我的理解中，rails非常适合小企业网站的开发，因为各方面原因大企业都不会轻易用rails开发网站。那么我以后如果去了大企业工作，它是否能起到重要作用呢？如果有作用，体现在哪些方面？
发自我的小米手机
在 Peter Wang notifications@github.com，2015年1月12日 下午9:16写道：@Wellaiyo 不用，你用的 github pages 就是支持 sass 的

**Comment by happypeter** [comment]
Rails 适合快速成型，所以小团队创业用是非常合适的。同时大公司也在用：
- Twitter 是用 Rails 开发的
- 团购鼻祖 groupon 也是
- ruby.taobao.com 是 ruby 中国镜像，我有朋友在阿里工作，他们也招 Rails 的人
- youku CSDN，github, new relic 这些中型企业也都在用 Rails

另外即使未来工作中不用 Rails，那 Rails 中学到的技巧也是可以用在其他语言环境下的，都是 Web 开发，都是相通的。就像 google 的人说，“We are not a ruby shop ... 但是有 Rails 经验的人我们也是很愿意要的”

**Comment by happypeter** [comment]
另，我服务的 oneapm.com 也不是小企业了，而且他们也不是主要用 Rails 的。

其实，未来大公司是一个逐渐消亡的过程，产业链，也就是多个小公司会取代大公司，这就是马云说的“因小而美”。创业要比去大公司工作更好。

**Comment by Wellaiyo** [comment]
看过一些sass的资料之后，感觉能改的就那么点东西（嵌套）。其它的我感觉挺麻烦的、完全没必要，可能是这个css文件不需要吧。变量、计算、代码重用这些东西貌似对于现在的我来说反而成了累赘呀

**Comment by Wellaiyo** [comment]
@happypeter 看下我的CSS文件，给点意见

**Comment by Wellaiyo** [comment]
@happypeter hi ,Peter. 你还没说我接下来的任务是什么呢，大概了解了sass之后，虽然还没弄懂具体怎么让我写的sass生效（估计后面当我真正需要它的时候，我能搞定它）。Next, What should i do?

**Comment by happypeter** [comment]
下一步要学习 git 这个工具，参考 http://happycasts.net/tag/git

**Comment by Wellaiyo** [comment]
今天偶然发现了Coding这个东西 ，http://coding.net 不知道你看过没

**Comment by Wellaiyo** [comment]
因为我的电脑是双系统的，实际操作环境Linux和现在常用的window分离了，所以可能在学git方面的实际操作会少很多。主要是去看，去了解，等到我实际要用的时候，我就知道整个流程中的每一步都是什么，不会可以去哪查资料 。你看这样行不？

**Comment by Wellaiyo** [comment]
你的视频我感觉还是太快了 ，我看的是这个http://www.liaoxuefeng.com/wiki/0013739516305929606dd18361248578c67b8067c8c017b000/0013744142037508cf42e51debf49668810645e02887691000

**Comment by happypeter** [comment]
最终就是以会用为目的，选择自己喜欢的资料就好。但是不动手肯定是不行的。

**Comment by Wellaiyo** [comment]
搞定了Git基础了 ，我知道怎么用命令行来修改操作github上的项目了，实践了一晚上。有个大神写了个Git Bash的软件 ，我现在就是在window上用它来操作的

**Comment by Wellaiyo** [comment]
@happypeter Peter ,帮我看下我最新写的文章2015-01-17-aboutCSS3.md怎么发布失败了

**Comment by happypeter** [comment]
@Wellaiyo 我也有时候会因为内容格式填写错误导致发布失败。

这个时候就要：
- 找到那次修改的版本
- 用 git 把这次修改 revert （回滚）
- 然后对应这次修改去看 jekyll 的文档，看看我到底错在哪里

**Comment by Wellaiyo** [comment]
我搞定了，我是用vim编辑器写的。后来我在github里面重新点击提交这篇文章就好了
发自我的小米手机
在 Peter Wang notifications@github.com，2015年1月19日 上午9:50写道：@Wellaiyo 我也有时候会因为内容格式填写错误导致发布失败。

这个时候就要：

找到那次修改的版本
用 git 把这次修改 revert （回滚）
然后对应这次修改去看 jekyll 的文档，看看我到底错在哪里

**Comment by happypeter** [comment]
牛！

**Comment by happypeter** [comment]
后面的提问可以到具体的仓库中了，比如关于你博客的提问，可以到你自己的那个 repo 里面提 issue ，然后 @我 就行了。

**Comment by Wellaiyo** [comment]
好的 ，我想知道我下一步该怎么做 。我学起来还是很快的

**Comment by happypeter** [comment]
@Wellaiyo 下一步学习 Ruby，了解，什么是 class object method 这些概念
